## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
global:
  # -- Global Docker image registry
  imageRegistry:
  # -- Global Docker registry secret names as an array
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  # -- Global StorageClass for Persistent Volume(s)
  storageClass:

# -- String to partially override common.names.fullname template (will maintain the release name)
##
nameOverride:

# -- String to fully override common.names.fullname template
##
fullnameOverride:

# -- Force target Kubernetes version (using Helm capabilites if not set)
##
kubeVersion:

##  service image version
## ref: https://github.com/open-hand/service
##
image:
  # -- service image registry
  registry: registry.cn-shanghai.aliyuncs.com
  # -- service image repository
  repository: c7n/service
  # -- (string) service image tag. Default Chart.AppVersion
  tag: ~
  # -- Specify a imagePullPolicy.
  # Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  # -- Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []

# -- Add labels to all the deployed resources
##
commonLabels: {}

# -- Add annotations to all the deployed resources
##
commonAnnotations: {}

## An array to add extra env vars
## e.g:
## extraEnv:
##   FOO: "bar"
##
extraEnv: {}

# -- ConfigMap with extra environment variables
##
extraEnvVarsCM: ""

# -- Secret with extra environment variables
##
extraEnvVarsSecret: ""

# -- Container's working directory(Default mountPath).
##
workingDir: 

# -- Command for running the service container (set to default if not set). Use array form
##
command: []

# -- Args for running the service container (set to default if not set). Use array form
##
args: []

# -- Scheduler name
## https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: 

# -- EnableServiceLinks indicates whether information about services should be injected into pod's environment variables, 
# matching the syntax of Docker links. Optional: Defaults to false.
## 
enableServiceLinks: false

# -- AutomountServiceAccountToken indicates whether a service account token should be automatically mounted.
## 
automountServiceAccountToken: false

## service deployment parameters
## The deployment strategy to use to replace existing pods with new ones.
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
## e.g:
## updateStrategy:
##  type: Recreate
##
updateStrategy:
  # -- Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
  type: RollingUpdate
  # -- Rolling update config params. Present only if DeploymentStrategyType = RollingUpdate.
  rollingUpdate:
    maxSurge: 100%
    maxUnavailable: 0

# -- Number of deployment replicas
##
replicaCount: 1

# -- service pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## service container ports to open
##
containerPort: 
  # --  server port
  serverPort: 8080

# -- Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 101
  runAsUser: 101

# -- Pod labels
## Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

# -- Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

# -- Pod affinity preset.
# Allowed values: soft, hard
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAffinityPreset: ""

# -- Pod anti-affinity preset.
# Allowed values: soft, hard
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft

## Node affinity preset.
## Allowed values: soft, hard
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  # -- Node affinity type.
  # Allowed values: soft, hard
  ##
  type: ""
  # -- Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  # -- Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

# -- Affinity for pod assignment. Evaluated as a template.
# Note: podAffinityPreset, podAntiAffinityPreset, and nodeAffinityPreset will be ignored when it's set
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

# -- Node labels for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

# -- Tolerations for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## service containers' resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.

  # -- The resources limits for the init container
  limits: {}
  #   cpu: 250m
  #   memory: 256Mi

  # -- The requested resources for the init container
  requests: {}
  #   cpu: 250m
  #   memory: 256Mi

## Configure extra options for liveness, readiness and startup probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
##
livenessProbe:
  # -- Enable livenessProbe
  enabled: true
  # -- Initial delay seconds for livenessProbe
  initialDelaySeconds: 180
  # -- Period seconds for livenessProbe
  periodSeconds: 5
  # -- Timeout seconds for livenessProbe
  timeoutSeconds: 5
  # -- Success threshold for livenessProbe
  successThreshold: 1
  # -- Failure threshold for livenessProbe
  failureThreshold: 5
readinessProbe:
  # -- Enable readinessProbe
  enabled: true
  # -- Initial delay seconds for readinessProbe
  initialDelaySeconds: 5
  # -- Period seconds for readinessProbe
  periodSeconds: 5
  # -- Timeout seconds for readinessProbe
  timeoutSeconds: 1
  # -- Success threshold for readinessProbe
  successThreshold: 1
  # -- Failure threshold for readinessProbe
  failureThreshold: 5
startupProbe:
  # -- Enable startupProbe
  enabled: false
  # -- Initial delay seconds for startupProbe
  initialDelaySeconds: 0
  # -- Period seconds for startupProbe
  periodSeconds: 10
  # -- Timeout seconds for startupProbe
  timeoutSeconds: 5
  # -- Success threshold for startupProbe
  successThreshold: 1
  # -- Failure threshold for startupProbe
  failureThreshold: 60

## Custom Liveness, Readiness, and Startup probes for service
##
# customLivenessProbe -- Custom Liveness
customLivenessProbe: {}
# -- Custom Readiness
customReadinessProbe: {}
# -- Custom Startup probes
customStartupProbe: {}

# -- Extra volumes to add to the service statefulset
##
extraVolumes: []

# -- Extra volume mounts to add to service containers
##
extraVolumeMounts: []

# -- Add init containers to the service pods.
## e.g:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers: {}

# -- Add sidecars to the service pods.
## e.g:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: {}

## service Service properties
##
service:
  # -- Set to true to enable service record generation
  ##
  enabled: true
  # -- service Service type
  ##
  type: ClusterIP
  # -- service Service port
  ##
  port: 8080
  # -- Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort: 
  # -- loadBalancerIP for the service Service (optional, cloud specific)
  ## ref: http://kubernetes.io/docs/user-guide/services/#type-loadbalancer
  ##
  loadBalancerIP:
  # -- Load Balancer sources
  ## https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## e.g:
  ## loadBalancerSourceRanges:
  ##   - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
  # -- Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  # -- Provide any additional annotations which may be required. This can be used to
  # set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}

## Configure the ingress resource that allows you to access the
## service installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  # -- Set to true to enable ingress record generation
  ##
  enabled: false

  # -- Set this to true in order to add the corresponding annotations for cert-manager
  ##
  certManager: false

  # -- Override API Version (automatically detected if not set)
  ##
  apiVersion:

  # -- When the ingress is enabled, a host pointing to this will be created
  ##
  hostname: server.local

  # -- The Path to service. You may need to set this to '/*' in order to use this
  # with ALB ingress controllers.
  ##
  path: /

  # -- Ingress Path type
  ##
  pathType: ImplementationSpecific

  # -- The service port to be used by this ingress.
  # Default is http. Alternative is https.
  ##
  servicePort: server

  # -- Ingress annotations done as key:value pairs
  # If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  ##
  ##
  annotations: {}

  # -- Enable TLS configuration for the hostname defined at ingress.hostname parameter
  ## TLS certificates will be retrieved from a TLS secret with name: {{- printf "%s-tls" .Values.ingress.hostname }}
  ## You can use the ingress.secrets parameter to create this TLS secret or relay on cert-manager to create it
  ##
  tls: false

  # -- The list of additional hostnames to be covered with this ingress record.
  ## Most likely the hostname above will be enough, but in the event more hosts are needed, this is an array
  ## e.g:
  ## extraHosts:
  ##   - name: server.local
  ##     path: /
  ##
  extraHosts: []

  # -- Any additional arbitrary paths that may need to be added to the ingress under the main host.
  ## For example: The ALB ingress controller requires a special rule for handling SSL redirection.
  ## extraPaths:
  ## - path: /*
  ##   backend:
  ##     serviceName: ssl-redirect
  ##     servicePort: use-annotation
  ##
  extraPaths: []

  # -- The tls configuration for additional hostnames to be covered with this ingress record.
  ## see: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
  ## e.g:
  ## extraTls:
  ## - hosts:
  ##     - server.local
  ##   secretName: server.local-tls
  ##
  extraTls: []

  # -- If you're providing your own certificates, please use this to add the certificates as secrets
  # key and certificate are expected in PEM format
  # name should line up with a secretName set further up
  ##
  ## If it is not set and you're using cert-manager, this is unneeded, as it will create a secret for you with valid certificates
  ## If it is not set and you're NOT using cert-manager either, self-signed certificates will be created valid for 365 days
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  ##
  ## Example
  ## secrets:
  ##   - name: server.local-tls
  ##     key: ""
  ##     certificate: ""
  ##
  secrets: []

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  # -- If true, use a Persistent Volume Claim, If false, use emptyDir
  ##
  enabled: false
  # -- Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: 

  # -- Data volume mount path
  ##
  mountPath: /data
  # -- Persistent Volume Access Mode
  ##
  accessModes:
    - ReadWriteMany
  # -- Persistent Volume size
  ##
  size: 8Gi
  # -- Persistent Volume Claim annotations
  ##
  annotations: {}
  # -- Enable persistence using an existing PVC
  ##
  existingClaim: 

# -- Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
volumePermissionsEnabled: false

## Specifies whether a ServiceAccount should be created
##
serviceAccount:
  # -- Set to true to create serviceAccount
  ##
  create: false
  # -- The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the common.names.fullname template
  ##
  name: ""
